packages:
  - apps/*
  - packages/*

engineStrict: true
savePrefix: ""

catalog:
  "@effect/vitest": 4.0.0-rc.112
  effect: 4.0.0-rc.112
  typescript: npm:@typescript/typescript6@6.0.2

allowBuilds:
  "@parcel/watcher": true
  "@swc/core": true
  esbuild: true
  msgpackr-extract: true
  protobufjs: true
  sharp: true

patchedDependencies:
  '@agentmail/convex@0.1.0': patches/@agentmail__convex@0.1.0.patch
