packages:
  - apps/*
  - packages/*

engineStrict: true
savePrefix: ""

catalog:
  "@effect/platform": 4.0.0-rc.110
  "@effect/platform-node": 4.0.0-rc.110
  "@effect/vitest": 4.0.0-rc.110
  effect: 4.0.0-rc.110
  typescript: npm:@typescript/typescript6@6.0.2

allowBuilds:
  "@parcel/watcher": true
  "@swc/core": true
  esbuild: true
  msgpackr-extract: true
  protobufjs: true
  sharp: true
